### ISSUE TITLE
DIscuss tech stack

### ISSUE THREAD

**Issue by siddhant1** [siddhant1/Learning-management-system#1]
We also need to discuss on the tech stack which will be used for this project.
My suggestions are the following

React.js -> frontend
Node.js -> backend
Redis -> Caching
Database -> MongoDB

Choose a design system to work as well
We also have some mockups which I will share links to

**Comment by siddhant1** [comment]
I recommend working with typescript for the frontend

**Comment by siddhant1** [comment]
@nik72619c @shakti97 @shivanshBTW have a look at this issue and let us start with this project soon

**Comment by nik72619c** [comment]
cool, lets not plugin typescript in for now

**Comment by siddhant1** [comment]
What other think about pluggin in typescript for this project,.
I think the project is big and we should use some kind of static type checking system

**Comment by shakti97** [comment]
Umm.. I also thinks we should use typescript

**Comment by nik72619c** [comment]
I think the inclusion of typescript is not needed to introduce type checking to the project

**Comment by siddhant1** [comment]
Let me know your final decision , I am up to start with anything

**Comment by shivanshBTW** [comment]
I think typescript will increase the complexity more when we don't need it
to

**Comment by shivanshBTW** [comment]
I am okay with it if you guys are going to use TS

**Comment by shivanshBTW** [comment]
but I would prefer without TS

**Comment by shivanshBTW** [comment]
decided the stack as
React Redux Typescript for frontend
NodeJS/ExpressJS and MongoDB for backend
