### ISSUE TITLE
Login Sign up page

### ISSUE THREAD

**Issue by shakti97** [siddhant1/Learning-management-system#22]
@shivanshBTW here, we want login and signup page for student, teacher

**Comment by minmaxdata** [comment]
do you want user management - what kind of authentication do you want to do and how do you plan on storing user information?

**Comment by minmaxdata** [comment]
Ill work on this

**Comment by rakeshlanjewarwork** [comment]
Please have a look at #23 
Let me know if any help needed

**Comment by rakeshlanjewarwork** [comment]
Please mark this as solved

**Comment by rakeshlanjewarwork** [comment]
If this issue has been solved then please close the issue!!!
